vaadin:
  launch-browser: true
spring:
  application.name: Spring Course
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: info
server:
  shutdown: graceful
