### Get Users
GET localhost:8080/v1/users

### Get User by id
GET localhost:8080/v1/users/3

### Create Users
POST localhost:8080/v1/users
Content-Type: application/json

{
  "email": "",
  "password": "129",
  "confirmPassword": "1234567",
  "age": 160,
  "phones": [
    {
      "phoneNumber": "234789"
    },
    {
      "phoneNumber": "789654"
    }
  ]
}

### Update User email
PATCH localhost:8080/v1/users/2/email
Content-Type: application/json

{
  "email" : "patchedmail@gmail.com"
}


### Update User
PUT localhost:8080/v1/users/3
Content-Type: application/json

{
  "email" : "springcourse3@gmail.com",
  "password" : "1234567",
  "confirmPassword" : "1234567"
}


### Delete User
DELETE localhost:8080/v1/users/3