@startuml
'https://plantuml.com/class-diagram

class BookEntity{
    - Long id;
    - String title;
    - String author;
    - String publisher;
    - Integer pages;
    - Genre genre;
    - Instant publishedAt;
    - Boolean available;
    + isNew()
}

enum Genre {
    SCI_FI,
    FANTASY,
    HORROR,
    OTHER
}

BookEntity --> Genre

@enduml